package com.revature.postComment;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "ForumNodes")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private int date_created;

    @DynamoDBAttribute
    private List<String> ancestors;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String parent;

    @DynamoDBAttribute
    private String subject;

}
