package com.revature.postComment;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@DynamoDBTable(tableName = "ForumNodes")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String owner;

    @DynamoDBAttribute
    private List<String> tags;

    @DynamoDBAttribute
    private String date_created = LocalDateTime.MIN.toString();

    @DynamoDBAttribute
    private List<String> ancestors;

    @DynamoDBAttribute
    private int child_count;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String parent;

    @DynamoDBAttribute
    private String subject;

}
